# Generated by Django 5.0.6 on 2026-05-12 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('internship', 'Internship'), ('contract', 'Contract'), ('freelance', 'Freelance')], default='full_time', max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('work_mode', models.CharField(choices=[('on_site', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='on_site', max_length=20)),
                ('start_date', models.CharField(help_text='e.g. 2024 or Mar 2024', max_length=20)),
                ('end_date', models.CharField(blank=True, help_text='Leave blank if current', max_length=20)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('dot_color', models.CharField(choices=[('red', 'Red'), ('green', 'Green')], default='red', max_length=10)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Experience',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='experience.experience')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='experience',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='experiences', to='experience.experiencetag'),
        ),
    ]
