# Generated by Django 5.0.6 on 2026-05-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WriteupTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('purple', 'Purple'), ('gray', 'Gray')], default='gray', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Writeup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb_label', models.CharField(help_text='Thumbnail text — use | for a line break (e.g. "CVE-2026|Linux")', max_length=40)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('excerpt', models.TextField()),
                ('content', models.TextField(blank=True, help_text='Full writeup body (Markdown supported)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='writeups/')),
                ('published_at', models.DateField()),
                ('read_time_min', models.PositiveIntegerField(default=5)),
                ('read_time_max', models.PositiveIntegerField(default=10)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('tags', models.ManyToManyField(blank=True, related_name='writeups', to='writeups.writeuptag')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
