# Generated by Django 5.0.6 on 2026-05-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('purple', 'Purple'), ('gray', 'Gray')], default='blue', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('authors', models.CharField(help_text='Comma-separated list of authors', max_length=500)),
                ('abstract', models.TextField(help_text='Full abstract of the paper')),
                ('short_description', models.TextField(help_text='Brief description shown on the card (max 300 chars)', max_length=300)),
                ('venue', models.CharField(help_text='Journal or conference name (e.g. "IEEE Access", "NDSS 2024")', max_length=200)),
                ('published_at', models.DateField()),
                ('publication_url', models.URLField(blank=True, help_text='Link to the paper on the publisher site (IEEE, ACM, etc.)')),
                ('certificate_image', models.ImageField(blank=True, help_text='Upload the publication certificate image', null=True, upload_to='research/certificates/')),
                ('is_featured', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tags', models.ManyToManyField(blank=True, related_name='papers', to='research.researchtag')),
            ],
            options={
                'ordering': ['order', '-published_at'],
            },
        ),
    ]
