# Generated by Django 5.0.6 on 2026-05-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hero_label', models.CharField(default="Hi, I'm a", max_length=100)),
                ('title_roles', models.TextField(default='Penetration Tester\nSecurity Researcher\nCTF Player\nEthical Hacker\nBug Hunter', help_text='One role per line — used for the typewriter animation')),
                ('bio', models.TextField()),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('profile_initials', models.CharField(default='YN', max_length=4)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('tryhackme_url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('response_note', models.TextField(blank=True, default='I typically respond to all inquiries within 24 hours. For urgent security matters, please call directly.')),
                ('footer_tagline', models.CharField(default='Stay curious. Stay ethical.', max_length=200)),
                ('footer_location', models.CharField(default='Dhaka', max_length=50)),
            ],
            options={
                'verbose_name': 'Site Profile',
                'verbose_name_plural': 'Site Profile',
            },
        ),
    ]
