# Generated by Django 5.0.6 on 2026-05-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeringorganization',
            name='logo_initials',
            field=models.CharField(blank=True, help_text='Short initials shown when no logo image is set, e.g. "IEEE"', max_length=6),
        ),
        migrations.AlterField(
            model_name='volunteeringorganization',
            name='total_duration',
            field=models.CharField(blank=True, help_text='e.g. "Jan 2023 – Present · 2 yrs"', max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteeringrole',
            name='achievements',
            field=models.TextField(blank=True, help_text='One achievement per line'),
        ),
        migrations.AlterField(
            model_name='volunteeringrole',
            name='end_date',
            field=models.CharField(blank=True, help_text='Leave blank if current role', max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteeringrole',
            name='start_date',
            field=models.CharField(help_text='e.g. "Jan 2025"', max_length=50),
        ),
    ]
