# Generated by Django 5.0.6 on 2026-05-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(help_text='Short label for sidebar tab', max_length=80)),
                ('category', models.CharField(max_length=100)),
                ('issuer', models.CharField(max_length=100)),
                ('issue_date', models.CharField(help_text='e.g. 2024 or Jun 2025', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('in_progress', 'In Progress')], default='active', max_length=20)),
                ('description', models.TextField()),
                ('cert_image', models.ImageField(blank=True, null=True, upload_to='certifications/')),
                ('credential_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Certification',
                'ordering': ['order'],
            },
        ),
    ]
